### ISSUE TITLE
How to make http proxy that connect to socks server.

### ISSUE THREAD

**Issue by shirshak55** [MoksS-zz/socks-v5#1]
I would like to create my own http proxy server thats support https transport.

```
import http from 'http'

const setting = {
  host: "127.0.0.1", // your socks 5 server
  port: "1080", // port your server
  login: "foo",
  password: "bar"
};

let server = http.createServer((req, res) => {

  res.pipe(...........what to do here)
})

server.listen(2345)
```

As its http proxy i think even https will go to (req,res) handler. But i don't know what should i pipe with res? 

Any help thanks.

**Comment by MoksS-zz** [comment]
you cannot pass encrypted https traffic through http / https modules.
Only your browser and destination server should know the keys, otherwise the data between your browser and the proxy server will not be protected and will be susceptible to a MITM attack.
For http proxies, when the connection is without encryption, you can leave the http module, as well as replace the headers and whatever you want.
For sites with https, only the tcp protocol, in which you can change the ip.

**Comment by shirshak55** [comment]
@MoksS hmm then how proxies work.I can use https in proxies right? Like i can connect to socks server etc directly and use https right? I don't want to decrypt just want to make proxy so that

Puppeteer-> HTTP Proxy -> Socks Proxy -> Website

Http Proxy so we can manage it easily and connect using most app. Socks proxy because i have bunch of socks server.

I did read socks rfc but i am still confused with bind and connect lol. And while investigating i found this package so thought you could help me.

Thanks.
